### ISSUE TITLE
Suggestion for a better name for the language detection function

### ISSUE THREAD

**Issue by AminTaheri23** [m3hrdadfi/zabanshenas#2]
I know `beshnas` is really cool in Persian, but it is not that tangible nor easy to spell from an English perspective. So I suggest to rename it or create a wrapper with a proper English name so that everyone can use it. 

By the way, thank you for the awesome rep. :)

**Comment by MinaHajirezaei** [comment]
Please help me
How can I save the zabanshenas model on my system and not every series needs to download the model from Link Git?
